version: "3"
services:
  cron:
    build:
      context: .
      dockerfile: Dockerfile
    command: CompileDaemon -log-prefix=false -build="make buildcron" -command="/app/dist/cron"
    env_file: ./.env
    volumes:
      - .:/app
    networks:
      - backend
  ldd:
    build:
      context: .
      dockerfile: Dockerfile
    command: CompileDaemon -log-prefix=false -build="make build" -command="./dist/api"
    env_file: ./.env
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - .:/app
    ports:
      - "12000:8080"
    networks:
      - backend
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: CompileDaemon -log-prefix=false -build="make buildmigrate" -command="/app/dist/migrations"
    volumes:
      - .:/app
    networks:
      - backend

networks:
  backend:
